# Generated by Django 6.0.2 on 2026-02-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=20),
        ),
    ]
